name: couchsurffing
description: "Code sample."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  injectable: 2.4.4
  get_it: 7.7.0
  go_router: 14.2.2
  flutter_bloc: 8.1.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: 6.8.0

flutter:

  uses-material-design: true
